name: Lint Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Note Notation
        run: |
          find . -name "*.md" -print0 | xargs -0 grep -E '^\\*\\*Note\\*\\*:'
          if [ $? -eq 0 ]; then
            echo "Error: Regex pattern found in markdown files."
            exit 1
          else
            echo "Lint check passed."
          fi
      - name: Check Warning Notation
        run: |
          find . -name "*.md" -print0 | xargs -0 grep -E '^\\*\\*Warning\\*\\*:'
          if [ $? -eq 0 ]; then
            echo "Error: Regex pattern found in markdown files."
            exit 1
          else
            echo "Lint check passed."
          fi
