name: Lint Check

on: push

jobs:
  lint:
    name: Lint markdown file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Find all .md files
      run: |
        find . -name "*.md" -type f -exec sh -c 'echo "${1#./}"' _ {} \; > markdown_files.txt
        cat markdown_files.txt
    - name: Lint markdown files
      run: |
        for file in $(cat markdown_files.txt); do
          echo "Linting $file"
          docker run --rm -v "$(pwd)/$file:/$file:ro" avtodev/markdown-lint:v1 --rules /linter/rules.js --config /linter/config.yml /$file
        done    
      # uses: docker://avtodev/markdown-lint:v1
      # with:
      #   rules: 'linter/rules.js'
      #   config: 'linter/config.yml'
      #   args: $(cat markdown_files.txt)