name: Lint Check

on: push

jobs:
  lint:
    name: Lint markdown file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Docker
      run: |
        apt-get update
        apt-get -y install docker.io
    - name: Lint Markdown files
      run: |
        docker run --rm \
          -v "$(pwd)/$file:/$file:ro" \
          avtodev/markdown-lint:v1 \
          --rules .github/linter/rules.js \
          --config .github/linter/config.yml \
          /Angular-Migration.md