name: Lint Check

on: push

jobs:
  lint:
    name: Lint markdown file
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install markdownlint
      run: npm install -g markdownlint

    - name: Lint Markdown files
      run: npx markdownlint . --config .markdownlint.json --rules linter/rules.js
    
    - name: Lint Markdown files_2.0
      run: markdownlint . --config .markdownlint.json --rules linter/rules.js