name: Lint Check

on: push

jobs:
  lint:
    name: Lint markdown file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        rules: 'linter/rules.js'
        config: 'linter/config.yml'