name: Lint Code Base
on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    
    - name: Super-Linter
      uses: github/super-linter@v4.10.0
      with:
        config: .markdownlint.json
        files: "*.md"
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_MARKDOWN: true
